# CircleCI Firebase Deployment Config
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Type Check
          command: yarn type-check
      - run:
          name: Build
          command: yarn build
  deploy:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-
      - run:
          name: Assume Github Role
          command: 'git config --global user.email "lshadler13@gmail.com"'
      - run:
          name: Deploy to server
          command: yarn deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop