version: 2
jobs:
  build:
    working_directory: ~/lshadler-github-io
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum yarn.lock" }}
      - run:
          name: Install 
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build